/**
 * `/news/new` — News has NO standalone create (the backend exposes no news create endpoint).
 * News records are created by publishing a completed event as news (codex §4.1). This route is an
 * honest guidance page that redirects the editor to the correct flow rather than faking an API.
 */
import Link from 'next/link';
import { Newspaper } from 'lucide-react';
import { PageHeader } from '@/components/layout/page-header';
import { EmptyState } from '@/components/feedback/empty-state';
import { Button } from '@/components/ui/button';
import { ROUTES } from '@/constants/routes';

export default function NewNewsRoute() {
  return (
    <div className="space-y-6">
      <PageHeader title="Create news" breadcrumbs={[{ label: 'News', href: ROUTES.news }, { label: 'New' }]} />
      <EmptyState
        icon={Newspaper}
        title="News is created from events"
        description="A news record is generated by publishing a completed event as news. Open the event and use “Publish as news” from its completion panel."
        action={
          <div className="flex gap-2">
            <Button asChild>
              <Link href={ROUTES.events}>Go to Events</Link>
            </Button>
            <Button asChild variant="outline">
              <Link href={ROUTES.news}>Back to News</Link>
            </Button>
          </div>
        }
      />
    </div>
  );
}
